---
# tasks file for mongodb
- name: Run apt upgrade
  apt:
    upgrade: "yes"
    update_cache: yes
    cache_valid_time: 432000

- name: Import public key
  apt_key:
    url: "https://www.mongodb.org/static/pgp/server-5.0.asc"
    state: present

- name: Add MongoDB repository
  apt_key:
    url: https://www.mongodb.org/static/pgp/server-5.0.asc
    state: present
  become: true

- name: Add MongoDB repository
  apt_repository:
    repo: "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/5.0 multiverse"
    state: present
    filename: mongodb-org-5.0.14
  become: true

- name: Install mongoDB
  apt:
    name: mongodb-org
    state: present
    update_cache: yes
  become: true

- name: Ensure mongodb is running and and enabled to start automatically on reboots
  service:
    name: mongod
    enabled: yes
    state: started

- name: Configure MongoDB for Graylog
  become: true
  copy:
    src: "templates/mongodb.conf.j2"
    dest: /etc/mongodb.conf
    owner: root
    group: root
    mode: "0644"
  notify:
    - restart mongodb

- name: Create Graylog MongoDB admin user
  mongodb_user:
    database: graylog
    name: douamgray
    password: "{{password}}"

    roles:
      [
        "readWriteAnyDatabase",
        "dbAdminAnyDatabase",
        "userAdminAnyDatabase",
        "clusterAdmin",
      ]
  become: true

- name: Initialize MongoDB Replica Set
  become: true
  shell: >
    mongo --eval "rs.initiate({_id: "graylog", members: [{_id: 0, host: "172.20.3.126:27017", priority: 2}, {_id: 1, host: "172.20.3.109:27017"}, {_id: 2, host: "172.20.3.55:27017"}]})"

- name: Wait for MongoDB Replica Set to become ready
  wait_for:
    port: 27017
    timeout: 300
