---
- name: "Mongodb main playbook"
  hosts: graylog
  remote_user: root

  roles:
    - mongodb
#
#- hosts: "graylog01"
#  tasks:
#    - name: "Install PyMongo"
#      apt:
#        update_cache: yes
#        name: "python3-pymongo"
#        state: "latest"

# - name: Configure replicaset
#   community.mongodb.mongodb_replicaset:
#     login_host: "douam"
#     replica_set: "graylog"
#     members:
#       - graylog01
#       - graylog02
#       - graylog03
