- name: Install Java Vim
  become: true
  apt:
    name:
      - openjdk-17-jdk-headless
      - vim
      - htop
      - apt-transport-https
      - python3
      - uuid-runtime
      - pwgen
      - curl
    update_cache: yes
    force: yes
    state: latest
    cache_valid_time: 86400
