---
- name: Run apt upgrade
  apt:
    upgrade: "yes"
    update_cache: yes
    cache_valid_time: 432000

- name: Add Graylog repository
  apt_key:
    url: https://packages.graylog2.org/repo/packages/graylog-5.0-repository_latest.deb.asc
    state: present
  become: true

- name: Add Graylog repository
  apt_repository:
    repo: "deb [arch=amd64] https://packages.graylog2.org/repo/packages graylog-5.0 main"
    state: present
    filename: graylog-5.0
  become: true

- name: Install Graylog
  become: true
  apt:
    name: graylog-server
    state: present
    update_cache: yes

- name: "Package 'apt-transport-https' should be installed"
  apt:
    name: "apt-transport-https"
    state: present

- name: Configure Graylog
  become: true
  copy:
    template:
    src: "templates/server.conf.j2"
    dest: /etc/graylog/server/server.conf
    owner: root
    group: root
    mode: "0644"
    notify:
      - restart graylog-server

- name: restart graylog
  service:
    name: graylog-server
    state: restarted
