---
- name: Run apt upgrade
  apt:
    upgrade: "yes"
    update_cache: yes
    cache_valid_time: 432000

- name: Download Graylog server package
  get_url:
    url: https://packages.graylog2.org/repo/packages/graylog-5.0.x/4.0/debian/pool/stable/g/graylog-server/graylog-server_5.0.1-1_all.deb
    dest: /tmp/graylog-server_5.0.1-1_all.deb

- name: Install Graylog server package
  command: dpkg -i graylog-5.0-repository_latest.deb

- name: Install Graylog
  become: true
  apt:
    name: graylog-server=5.0.1-1
    state: present
    update_cache: yes

- name: Enable Graylog server service
  systemd:
    name: graylog-server
    enabled: yes
    state: started

- name: Configure Graylog
  copy:
    src: "templates/server.conf.j2"
    dest: /etc/graylog/server/server.conf
    owner: root
    group: root
    mode: "0644"

- name: restart graylog
  service:
    name: graylog-server
    state: restarted
