---
- name: Install Elasticsearch
  become: true
  apt:
    name: elasticsearch
    state: present

- name: Configure Elasticsearch
  copy:
    src: elasticsearch.j2
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: root
    group: root
    mode: "0644"
  notify:
    - restart elasticsearch

- name: restart elasticsearch
  service:
    name: elasticsearch
    state: restarted
